In [15]:
#Problem 1
#Matrix Manipulations

In [2]:
import numpy as np

In [5]:
A = np.array([[3,5, 9], [3, 3, 4],[5,9,17]])

In [6]:
print(A)

[[ 3  5  9]
 [ 3  3  4]
 [ 5  9 17]]


In [7]:
B=np.array([[2],[1],[4]])

In [8]:
print (B)

[[2]
 [1]
 [4]]


In [9]:
x = np.linalg.solve(A, B)

In [14]:
print(x)

[[ 1.]
 [-2.]
 [ 1.]]


In [17]:
#Problem 2
#Create a result array by adding the following two NumPy arrays.
#Next, modify the result array by calculating the square of each element Input:

In [18]:
import numpy as np

In [19]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

In [23]:
result_array = arrayOne + arrayTwo

In [24]:
print(result_array)

[[20 39 33]
 [25 25 28]]


In [21]:
result_array_squared = np.square(result_array)

In [25]:
print("\nResult Array Squared (square of each element):")


Result Array Squared (square of each element):


In [26]:
print(result_array_squared)

[[ 400 1521 1089]
 [ 625  625  784]]


In [28]:
#Problem3
#Print max from axis 0 and min from axis 1 from the following 2-D array.

In [29]:
import numpy as np

In [30]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

In [31]:
max_axis_0 = np.max(sampleArray, axis=0)

In [32]:
min_axis_1 = np.min(sampleArray, axis=1)

In [33]:
print("Max along axis 0:")
print(max_axis_0)

Max along axis 0:
[82 94 73]


In [34]:
print("\nMin along axis 1:")
print(min_axis_1)


Min along axis 1:
[34 12 53]


In [39]:
#Problem 4
#Get the positions where elements of a and b match
#Input: a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#Desired Output: array([1, 3, 5, 7])

In [35]:
import numpy as np

In [36]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [37]:
matching_positions = np.where(a == b)[0]


In [38]:
print("Desired Output:")
print(matching_positions)

Desired Output:
[1 3 5 7]


In [40]:
import numpy as np

In [41]:
 a= np.array([[1, 2], [3, 4]])
b= np.array([[5, 6], [7, 8]])

In [45]:
merged_matrix_vertical = np.concatenate((a,b), axis=0)

In [46]:
print("c=")
print(merged_matrix_vertical)

c=
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
merged_matrix_horizontal = np.concatenate((a,b), axis=1)

In [48]:
print("d=")
print(merged_matrix_horizontal)

d=
[[1 2 5 6]
 [3 4 7 8]]
